/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microsoft_mgl_smithwaterman_MicrosoftSmithWaterman */

#ifndef _Included_com_microsoft_mgl_smithwaterman_MicrosoftSmithWaterman
#define _Included_com_microsoft_mgl_smithwaterman_MicrosoftSmithWaterman
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microsoft_mgl_smithwaterman_MicrosoftSmithWaterman
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_microsoft_mgl_smithwaterman_MicrosoftSmithWaterman_initNative
  (JNIEnv *, jclass);

/*
 * Class:     com_microsoft_mgl_smithwaterman_MicrosoftSmithWaterman
 * Method:    alignNative
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_microsoft_mgl_smithwaterman_MicrosoftSmithWaterman_alignNative
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_microsoft_mgl_smithwaterman_MicrosoftSmithWaterman
 * Method:    doneNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_microsoft_mgl_smithwaterman_MicrosoftSmithWaterman_doneNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
