# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self  # self represents the repo where the initial Pipelines YAML file was found
  submodules: true
- task: ShellScript@2
  inputs:
    scriptPath: ./vcpkg/bootstrap-vcpkg.sh

- script: ./vcpkg/vcpkg install tbb
  displayName: 'Install TBB'
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    options: '--info'
    tasks: 'publish'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false
  env:
    ORG_GRADLE_PROJECT_signingKey: $(ORG_GRADLE_PROJECT_signingKey)
    ORG_GRADLE_PROJECT_signingPassword: $(ORG_GRADLE_PROJECT_signingPassword)
    ORG_GRADLE_PROJECT_sonatypeUsername: $(ORG_GRADLE_PROJECT_sonatypeUsername)
    ORG_GRADLE_PROJECT_sonatypePassword: $(ORG_GRADLE_PROJECT_sonatypePassword)