/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microsoft_mgl_pairhmm_MicrosoftPairHmm */

#ifndef _Included_com_microsoft_mgl_pairhmm_MicrosoftPairHmm
#define _Included_com_microsoft_mgl_pairhmm_MicrosoftPairHmm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microsoft_mgl_pairhmm_MicrosoftPairHmm
 * Method:    initNative
 * Signature: (ZI)V
 */
JNIEXPORT void JNICALL Java_com_microsoft_mgl_pairhmm_MicrosoftPairHmm_initNative
  (JNIEnv *, jclass, jboolean, jint);

/*
 * Class:     com_microsoft_mgl_pairhmm_MicrosoftPairHmm
 * Method:    computeLikelihoodsNative
 * Signature: (Ljava/nio/IntBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_microsoft_mgl_pairhmm_MicrosoftPairHmm_computeLikelihoodsNative
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     com_microsoft_mgl_pairhmm_MicrosoftPairHmm
 * Method:    doneNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_microsoft_mgl_pairhmm_MicrosoftPairHmm_doneNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
